services:
  backend:
    build:
      context: ./shohojcart_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:6jOugj61MaYxk0nfX9dlft9id+T06J7ts681Vs06aLg=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      # Remote MySQL Database
      - DB_CONNECTION=mysql
      - DB_HOST=46.4.222.212
      - DB_PORT=3306
      - DB_DATABASE=abstract_shohojcart
      - DB_USERNAME=abstract_shohojcart
      - DB_PASSWORD=abstract_shohojcart
      # Session and CORS for local frontend
      - SESSION_DRIVER=cookie
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:5173
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./shohojcart_backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    restart: unless-stopped