services:
  - type: web
    name: shohojcart-backend
    env: docker
    dockerfilePath: ./shohojcart_backend/Dockerfile
    dockerContext: ./shohojcart_backend
    plan: free
    envVars:
      # App Configuration
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:6jOugj61MaYxk0nfX9dlft9id+T06J7ts681Vs06aLg=
      - key: APP_URL
        fromService:
          type: web
          name: shohojcart-backend
          property: host

      # Logging
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: REQUIRE_EMAIL_VERIFICATION
        value: true

      # Database Configuration (from .env)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 46.4.222.212
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: abstract_shohojcart
      - key: DB_USERNAME
        value: abstract_shohojcart
      - key: DB_PASSWORD
        value: abstract_shohojcart

      # Cache and Session
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_LIFETIME
        value: 120

      # CORS / Sanctum (Update these for production)
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
      - key: SANCTUM_STATEFUL_DOMAINS
        value: your-frontend-domain.com
      - key: SESSION_DOMAIN
        value: your-backend-domain.com
      - key: SESSION_SECURE_COOKIE
        value: true

      # Mail Configuration
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Laravel

    healthCheckPath: /
    autoDeploy: true
    postDeployCommand: |
      php artisan key:generate --force
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
